Initial PR
eastgenomics/clinvar_submissions pull request #1
Opened 2024-09-19 11:14 UTC by kjwinfield

This PR includes content from:

- eggd_pandora (https://github.com/eastgenomics/eggd_pandora/)
- submit_variants_INCA (https://github.com/eastgenomics/submit_variants_INCA/)
- variant_workbook_parser (https://github.com/eastgenomics/variant_workbook_parser/)

Elements of all these scripts have been merged together to make this an all-in-one process

2024-09-19 11:14 UTC, pep8speaks commented
Hello @kjwinfield! Thanks for opening this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:

* In the file [`pandora.py`](https://github.com/eastgenomics/clinvar_submissions/blob/b4ad79fde51fc2c155fa1afbfa6946fe31fd4cfc/pandora.py):

> [Line 16:1](https://github.com/eastgenomics/clinvar_submissions/blob/b4ad79fde51fc2c155fa1afbfa6946fe31fd4cfc/pandora.py#L16): [E302](https://duckduckgo.com/?q=pep8%20E302) expected 2 blank lines, found 1
> [Line 41:5](https://github.com/eastgenomics/clinvar_submissions/blob/b4ad79fde51fc2c155fa1afbfa6946fe31fd4cfc/pandora.py#L41): [E265](https://duckduckgo.com/?q=pep8%20E265) block comment should start with '# '
> [Line 44:30](https://github.com/eastgenomics/clinvar_submissions/blob/b4ad79fde51fc2c155fa1afbfa6946fe31fd4cfc/pandora.py#L44): [E711](https://duckduckgo.com/?q=pep8%20E711) comparison to None should be 'if cond is None:'
> [Line 57:13](https://github.com/eastgenomics/clinvar_submissions/blob/b4ad79fde51fc2c155fa1afbfa6946fe31fd4cfc/pandora.py#L57): [E122](https://duckduckgo.com/?q=pep8%20E122) continuation line missing indentation or outdented
> [Line 60:13](https://github.com/eastgenomics/clinvar_submissions/blob/b4ad79fde51fc2c155fa1afbfa6946fe31fd4cfc/pandora.py#L60): [E122](https://duckduckgo.com/?q=pep8%20E122) continuation line missing indentation or outdented
> [Line 61:13](https://github.com/eastgenomics/clinvar_submissions/blob/b4ad79fde51fc2c155fa1afbfa6946fe31fd4cfc/pandora.py#L61): [E122](https://duckduckgo.com/?q=pep8%20E122) continuation line missing indentation or outdented
> [Line 63:10](https://github.com/eastgenomics/clinvar_submissions/blob/b4ad79fde51fc2c155fa1afbfa6946fe31fd4cfc/pandora.py#L63): [W291](https://duckduckgo.com/?q=pep8%20W291) trailing whitespace
> [Line 87:80](https://github.com/eastgenomics/clinvar_submissions/blob/b4ad79fde51fc2c155fa1afbfa6946fe31fd4cfc/pandora.py#L87): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (86 > 79 characters)
> [Line 136:13](https://github.com/eastgenomics/clinvar_submissions/blob/b4ad79fde51fc2c155fa1afbfa6946fe31fd4cfc/pandora.py#L136): [E122](https://duckduckgo.com/?q=pep8%20E122) continuation line missing indentation or outdented
> [Line 137:13](https://github.com/eastgenomics/clinvar_submissions/blob/b4ad79fde51fc2c155fa1afbfa6946fe31fd4cfc/pandora.py#L137): [E122](https://duckduckgo.com/?q=pep8%20E122) continuation line missing indentation or outdented
> [Line 138:13](https://github.com/eastgenomics/clinvar_submissions/blob/b4ad79fde51fc2c155fa1afbfa6946fe31fd4cfc/pandora.py#L138): [E122](https://duckduckgo.com/?q=pep8%20E122) continuation line missing indentation or outdented
> [Line 170:80](https://github.com/eastgenomics/clinvar_submissions/blob/b4ad79fde51fc2c155fa1afbfa6946fe31fd4cfc/pandora.py#L170): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (80 > 79 characters)
> [Line 189:1](https://github.com/eastgenomics/clinvar_submissions/blob/b4ad79fde51fc2c155fa1afbfa6946fe31fd4cfc/pandora.py#L189): [E302](https://duckduckgo.com/?q=pep8%20E302) expected 2 blank lines, found 1
> [Line 208:1](https://github.com/eastgenomics/clinvar_submissions/blob/b4ad79fde51fc2c155fa1afbfa6946fe31fd4cfc/pandora.py#L208): [E303](https://duckduckgo.com/?q=pep8%20E303) too many blank lines (3)
> [Line 221:6](https://github.com/eastgenomics/clinvar_submissions/blob/b4ad79fde51fc2c155fa1afbfa6946fe31fd4cfc/pandora.py#L221): [W291](https://duckduckgo.com/?q=pep8%20W291) trailing whitespace
> [Line 255:80](https://github.com/eastgenomics/clinvar_submissions/blob/b4ad79fde51fc2c155fa1afbfa6946fe31fd4cfc/pandora.py#L255): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (85 > 79 characters)
> [Line 303:70](https://github.com/eastgenomics/clinvar_submissions/blob/b4ad79fde51fc2c155fa1afbfa6946fe31fd4cfc/pandora.py#L303): [W291](https://duckduckgo.com/?q=pep8%20W291) trailing whitespace
> [Line 311:80](https://github.com/eastgenomics/clinvar_submissions/blob/b4ad79fde51fc2c155fa1afbfa6946fe31fd4cfc/pandora.py#L311): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (86 > 79 characters)
> [Line 315:11](https://github.com/eastgenomics/clinvar_submissions/blob/b4ad79fde51fc2c155fa1afbfa6946fe31fd4cfc/pandora.py#L315): [W292](https://duckduckgo.com/?q=pep8%20W292) no newline at end of file

* In the file [`utils/utils.py`](https://github.com/eastgenomics/clinvar_submissions/blob/b4ad79fde51fc2c155fa1afbfa6946fe31fd4cfc/utils/utils.py):

> [Line 14:1](https://github.com/eastgenomics/clinvar_submissions/blob/b4ad79fde51fc2c155fa1afbfa6946fe31fd4cfc/utils/utils.py#L14): [E302](https://duckduckgo.com/?q=pep8%20E302) expected 2 blank lines, found 1
> [Line 109:5](https://github.com/eastgenomics/clinvar_submissions/blob/b4ad79fde51fc2c155fa1afbfa6946fe31fd4cfc/utils/utils.py#L109): [E303](https://duckduckgo.com/?q=pep8%20E303) too many blank lines (2)
> [Line 140:1](https://github.com/eastgenomics/clinvar_submissions/blob/b4ad79fde51fc2c155fa1afbfa6946fe31fd4cfc/utils/utils.py#L140): [E302](https://duckduckgo.com/?q=pep8%20E302) expected 2 blank lines, found 1
> [Line 195:1](https://github.com/eastgenomics/clinvar_submissions/blob/b4ad79fde51fc2c155fa1afbfa6946fe31fd4cfc/utils/utils.py#L195): [E302](https://duckduckgo.com/?q=pep8%20E302) expected 2 blank lines, found 1
> [Line 359:1](https://github.com/eastgenomics/clinvar_submissions/blob/b4ad79fde51fc2c155fa1afbfa6946fe31fd4cfc/utils/utils.py#L359): [E302](https://duckduckgo.com/?q=pep8%20E302) expected 2 blank lines, found 1
> [Line 379:1](https://github.com/eastgenomics/clinvar_submissions/blob/b4ad79fde51fc2c155fa1afbfa6946fe31fd4cfc/utils/utils.py#L379): [E302](https://duckduckgo.com/?q=pep8%20E302) expected 2 blank lines, found 1
> [Line 475:1](https://github.com/eastgenomics/clinvar_submissions/blob/b4ad79fde51fc2c155fa1afbfa6946fe31fd4cfc/utils/utils.py#L475): [E302](https://duckduckgo.com/?q=pep8%20E302) expected 2 blank lines, found 1
> [Line 594:1](https://github.com/eastgenomics/clinvar_submissions/blob/b4ad79fde51fc2c155fa1afbfa6946fe31fd4cfc/utils/utils.py#L594): [E302](https://duckduckgo.com/?q=pep8%20E302) expected 2 blank lines, found 1
> [Line 655:27](https://github.com/eastgenomics/clinvar_submissions/blob/b4ad79fde51fc2c155fa1afbfa6946fe31fd4cfc/utils/utils.py#L655): [W292](https://duckduckgo.com/?q=pep8%20W292) no newline at end of file

2024-09-19 13:25 UTC, Yu-jinKim requested changes
> Reviewed 4 of 7 files at r1, 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/clinvar_submissions/1)* status: all files reviewed, 44 unresolved discussions (waiting on @kjwinfield)

___
*[`pandora.py` line 17 at r2](https://reviewable.io/reviews/eastgenomics/clinvar_submissions/1#-O798Ote6SLRwhM5wJ9A:-O798Otf5cCeN29bpFeE:b-t188av) ([raw file](https://github.com/eastgenomics/clinvar_submissions/blob/c5341cb51fd9bdc1aa81c4756315efe540276e8e/pandora.py#L17)):*
> ```Python
> 
> 
> def parp_inhibitor_submission(clinvar_dict):
> ```

while this is the end goal after modifying the dictionary, it doesn't reflect what the function actually does i.e. add info pertaining to the R444
___
*[`pandora.py` line 19 at r2](https://reviewable.io/reviews/eastgenomics/clinvar_submissions/1#-O797iqG27beQXLUA7lk:-O797iqG27beQXLUA7ll:bzd29wi) ([raw file](https://github.com/eastgenomics/clinvar_submissions/blob/c5341cb51fd9bdc1aa81c4756315efe540276e8e/pandora.py#L19)):*
> ```Python
> def parp_inhibitor_submission(clinvar_dict):
>     '''
>     Edit clinvar_submission dict to add drug responsiveness information if this
> ```

need to complete docstring
___
*[`pandora.py` line 27 at r2](https://reviewable.io/reviews/eastgenomics/clinvar_submissions/1#-O797u186gpMtaTVCjFm:-O797u19BLcanewxlFx_:b-awkrjp) ([raw file](https://github.com/eastgenomics/clinvar_submissions/blob/c5341cb51fd9bdc1aa81c4756315efe540276e8e/pandora.py#L27)):*
> ```Python
>         'clinicalSignificanceDescription'
>     ]
>     translate = {
> ```

not used within the function
___
*[`pandora.py` line 46 at r2](https://reviewable.io/reviews/eastgenomics/clinvar_submissions/1#-O7980t4Bm-OKcmN0T6v:-O7980t4Bm-OKcmN0T6w:b6tnjzp) ([raw file](https://github.com/eastgenomics/clinvar_submissions/blob/c5341cb51fd9bdc1aa81c4756315efe540276e8e/pandora.py#L46)):*
> ```Python
>     # if can't be translated, stop + add error to db
>     if drug_response_details == None:
>         query = ("db error! value not translateable")
> ```

how is the error added to the db?
___
*[`pandora.py` line 70 at r2](https://reviewable.io/reviews/eastgenomics/clinvar_submissions/1#-O798iIL0OtHB0qZLzpK:-O798iIL0OtHB0qZLzpL:b97ekly) ([raw file](https://github.com/eastgenomics/clinvar_submissions/blob/c5341cb51fd9bdc1aa81c4756315efe540276e8e/pandora.py#L70)):*
> ```Python
> 
> 
> def extract_clinvar_information(variant):
> ```

can the variable be renamed variant_row or something that reflects the data structure?
___
*[`pandora.py` line 78 at r2](https://reviewable.io/reviews/eastgenomics/clinvar_submissions/1#-O799AJGAR9A8GSEBc9Y:-O799AJH0gnAaMXY5-9f:b-ptnv9f) ([raw file](https://github.com/eastgenomics/clinvar_submissions/blob/c5341cb51fd9bdc1aa81c4756315efe540276e8e/pandora.py#L78)):*
> ```Python
>         clinvar_dict: dictionary of data to submit to clinvar
>     '''
>     if str(variant["Comment on classification"]) == "nan":
> ```

https://pandas.pydata.org/docs/reference/api/pandas.isna.html#pandas.isna
feels more robust
___
*[`pandora.py` line 79 at r2](https://reviewable.io/reviews/eastgenomics/clinvar_submissions/1#-O799DkrEl1zh1iMaWHO:-O799DkrEl1zh1iMaWHP:bipv7ay) ([raw file](https://github.com/eastgenomics/clinvar_submissions/blob/c5341cb51fd9bdc1aa81c4756315efe540276e8e/pandora.py#L79)):*
> ```Python
>     '''
>     if str(variant["Comment on classification"]) == "nan":
>         variant["Comment on classification"] = "None"
> ```

none string? do we want that?
___
*[`pandora.py` line 82 at r2](https://reviewable.io/reviews/eastgenomics/clinvar_submissions/1#-O799RIM8aSTxmg1XsQc:-O799RIN3sgHJUizaB2C:b1gz0x9) ([raw file](https://github.com/eastgenomics/clinvar_submissions/blob/c5341cb51fd9bdc1aa81c4756315efe540276e8e/pandora.py#L82)):*
> ```Python
> 
>     if variant["Ref_genome"] not in ["GRCh37.p13", "GRCh38.p13"]:
>         raise RuntimeError("Invalid genome build")
> ```

inaccurate error raised, could just be a base exception
___
*[`pandora.py` line 161 at r2](https://reviewable.io/reviews/eastgenomics/clinvar_submissions/1#-O79AiwI76mdXYvYnZ1e:-O79AiwJ8H8ZdOMamZ85:b-sgh1ns) ([raw file](https://github.com/eastgenomics/clinvar_submissions/blob/c5341cb51fd9bdc1aa81c4756315efe540276e8e/pandora.py#L161)):*
> ```Python
> 
> 
> def add_variants_to_db(df, cursor, conn):
> ```

this function does 2 things:
- format data to extract information
- submit said information to the database
probably could be 2 functions
___
*[`pandora.py` line 175 at r2](https://reviewable.io/reviews/eastgenomics/clinvar_submissions/1#-O79AxRE0x8_8CD3xrtG:-O79AxRE0x8_8CD3xrtH:bh8k6w7) ([raw file](https://github.com/eastgenomics/clinvar_submissions/blob/c5341cb51fd9bdc1aa81c4756315efe540276e8e/pandora.py#L175)):*
> ```Python
>         item_to_insert = []
>         for item in list(temp_df.iloc[0]):
>             if isinstance(item, np.int64):
> ```

numpy not imported
___
*[`pandora.py` line 193 at r2](https://reviewable.io/reviews/eastgenomics/clinvar_submissions/1#-O79B7T85TyRHz5FDbcs:-O79B7T85TyRHz5FDbct:b-uurejc) ([raw file](https://github.com/eastgenomics/clinvar_submissions/blob/c5341cb51fd9bdc1aa81c4756315efe540276e8e/pandora.py#L193)):*
> ```Python
> def parse_args():
>     parser = argparse.ArgumentParser(
>                             description="",
> ```

why is it formatted like that?
```
parser = argparse.ArgumentParser(
        description="",
        formatter_class=(
            argparse.ArgumentDefaultsHelpFormatter
        )
    )
```
___
*[`pandora.py` line 199 at r2](https://reviewable.io/reviews/eastgenomics/clinvar_submissions/1#-O79BLi3BlOfHjFRnCo2:-O79BLi3BlOfHjFRnCo3:b-7xsw94) ([raw file](https://github.com/eastgenomics/clinvar_submissions/blob/c5341cb51fd9bdc1aa81c4756315efe540276e8e/pandora.py#L199)):*
> ```Python
>                         )
>     # TODO add help strings
>     parser.add_argument('--clinvar_api_key') # TODO delete this? find a better way of passing the API key?
> ```

can have a chat about that if needed
___
*[`pandora.py` line 209 at r2](https://reviewable.io/reviews/eastgenomics/clinvar_submissions/1#-O79BeOI5UjAClOy63Dv:-O79BeOI5UjAClOy63Dw:b9ycrl) ([raw file](https://github.com/eastgenomics/clinvar_submissions/blob/c5341cb51fd9bdc1aa81c4756315efe540276e8e/pandora.py#L209)):*
> ```Python
> 
> 
> def main():
> ```

your main is really bloated, with parsing of files, database stuff and pandas stuff going on. A lot can be put in functions
___
*[`pandora.py` line 215 at r2](https://reviewable.io/reviews/eastgenomics/clinvar_submissions/1#-O79BxCmCJRo-h8xKQp_:-O79BxCmCJRo-h8xKQpa:b-eg4r5i) ([raw file](https://github.com/eastgenomics/clinvar_submissions/blob/c5341cb51fd9bdc1aa81c4756315efe540276e8e/pandora.py#L215)):*
> ```Python
>     args = parse_args()
>     print(f"Searching {args.path_to_workbooks}...")
>     workbooks = glob.glob(args.path_to_workbooks + "*.xlsx")
> ```

i would try and keep related things close i.e. move this line just before it's used
___
*[`pandora.py` line 216 at r2](https://reviewable.io/reviews/eastgenomics/clinvar_submissions/1#-O79C35cAH4M-opc12W4:-O79C35cAH4M-opc12W5:bydr7yz) ([raw file](https://github.com/eastgenomics/clinvar_submissions/blob/c5341cb51fd9bdc1aa81c4756315efe540276e8e/pandora.py#L216)):*
> ```Python
>     print(f"Searching {args.path_to_workbooks}...")
>     workbooks = glob.glob(args.path_to_workbooks + "*.xlsx")
>     with open(args.config) as f:
> ```

can probably become a generic json loading function
___
*[`pandora.py` line 219 at r2](https://reviewable.io/reviews/eastgenomics/clinvar_submissions/1#-O79C8m80fN_u-1XyYjR:-O79C8m80fN_u-1XyYjS:b-1lpt05) ([raw file](https://github.com/eastgenomics/clinvar_submissions/blob/c5341cb51fd9bdc1aa81c4756315efe540276e8e/pandora.py#L219)):*
> ```Python
>         config = json.load(f)
> 
>     conn_str = (
> ```

move this into a function and return the cursor
___
*[`pandora.py` line 234 at r2](https://reviewable.io/reviews/eastgenomics/clinvar_submissions/1#-O79CQ0v126fznQ9G [...]

2024-09-20 11:14 UTC, kjwinfield reviewed
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/clinvar_submissions/1)* status: 4 of 7 files reviewed, 44 unresolved discussions (waiting on @Yu-jinKim)

___
*[`pandora.py` line 17 at r2](https://reviewable.io/reviews/eastgenomics/clinvar_submissions/1#-O798Ote6SLRwhM5wJ9A:-O79sw2OB4YSDCBoBiNc:b-896fix) ([raw file](https://github.com/eastgenomics/clinvar_submissions/blob/c5341cb51fd9bdc1aa81c4756315efe540276e8e/pandora.py#L17)):*
<details><summary><i>Previously, Yu-jinKim wrote…</i></summary><blockquote>

while this is the end goal after modifying the dictionary, it doesn't reflect what the function actually does i.e. add info pertaining to the R444
</blockquote></details>

Done.
___
*[`pandora.py` line 19 at r2](https://reviewable.io/reviews/eastgenomics/clinvar_submissions/1#-O797iqG27beQXLUA7lk:-O79swVa1L_MuozP2FKP:b-896fix) ([raw file](https://github.com/eastgenomics/clinvar_submissions/blob/c5341cb51fd9bdc1aa81c4756315efe540276e8e/pandora.py#L19)):*
<details><summary><i>Previously, Yu-jinKim wrote…</i></summary><blockquote>

need to complete docstring
</blockquote></details>

Done.
___
*[`pandora.py` line 27 at r2](https://reviewable.io/reviews/eastgenomics/clinvar_submissions/1#-O797u186gpMtaTVCjFm:-O79t4p_-fIxdQJk1re_:b-896fix) ([raw file](https://github.com/eastgenomics/clinvar_submissions/blob/c5341cb51fd9bdc1aa81c4756315efe540276e8e/pandora.py#L27)):*
<details><summary><i>Previously, Yu-jinKim wrote…</i></summary><blockquote>

not used within the function
</blockquote></details>

Done.
___
*[`pandora.py` line 46 at r2](https://reviewable.io/reviews/eastgenomics/clinvar_submissions/1#-O7980t4Bm-OKcmN0T6v:-O79t5uJ0FAaT6yzAYSt:b-896fix) ([raw file](https://github.com/eastgenomics/clinvar_submissions/blob/c5341cb51fd9bdc1aa81c4756315efe540276e8e/pandora.py#L46)):*
<details><summary><i>Previously, Yu-jinKim wrote…</i></summary><blockquote>

how is the error added to the db?
</blockquote></details>

Done.
___
*[`pandora.py` line 70 at r2](https://reviewable.io/reviews/eastgenomics/clinvar_submissions/1#-O798iIL0OtHB0qZLzpK:-O79t72M9E1G8eluprg_:b-896fix) ([raw file](https://github.com/eastgenomics/clinvar_submissions/blob/c5341cb51fd9bdc1aa81c4756315efe540276e8e/pandora.py#L70)):*
<details><summary><i>Previously, Yu-jinKim wrote…</i></summary><blockquote>

can the variable be renamed variant_row or something that reflects the data structure?
</blockquote></details>

Done.
___
*[`pandora.py` line 78 at r2](https://reviewable.io/reviews/eastgenomics/clinvar_submissions/1#-O799AJGAR9A8GSEBc9Y:-O79t8NzD3JCxyYKNNTV:b-896fix) ([raw file](https://github.com/eastgenomics/clinvar_submissions/blob/c5341cb51fd9bdc1aa81c4756315efe540276e8e/pandora.py#L78)):*
<details><summary><i>Previously, Yu-jinKim wrote…</i></summary><blockquote>

https://pandas.pydata.org/docs/reference/api/pandas.isna.html#pandas.isna
feels more robust
</blockquote></details>

Done.
___
*[`pandora.py` line 79 at r2](https://reviewable.io/reviews/eastgenomics/clinvar_submissions/1#-O799DkrEl1zh1iMaWHO:-O7E1l9N16cIQ41CAZCV:b-896fix) ([raw file](https://github.com/eastgenomics/clinvar_submissions/blob/c5341cb51fd9bdc1aa81c4756315efe540276e8e/pandora.py#L79)):*
<details><summary><i>Previously, Yu-jinKim wrote…</i></summary><blockquote>

none string? do we want that?
</blockquote></details>

Done.
___
*[`pandora.py` line 82 at r2](https://reviewable.io/reviews/eastgenomics/clinvar_submissions/1#-O799RIM8aSTxmg1XsQc:-O79tOBn8C6QYw8vAiIk:b-uo4afy) ([raw file](https://github.com/eastgenomics/clinvar_submissions/blob/c5341cb51fd9bdc1aa81c4756315efe540276e8e/pandora.py#L82)):*
<details><summary><i>Previously, Yu-jinKim wrote…</i></summary><blockquote>

inaccurate error raised, could just be a base exception
</blockquote></details>

Done. Changed to value error, assuming that is appropriate
___
*[`pandora.py` line 161 at r2](https://reviewable.io/reviews/eastgenomics/clinvar_submissions/1#-O79AiwI76mdXYvYnZ1e:-O7E1mWs2q5b1AvgGJgk:bjzc0r8) ([raw file](https://github.com/eastgenomics/clinvar_submissions/blob/c5341cb51fd9bdc1aa81c4756315efe540276e8e/pandora.py#L161)):*
<details><summary><i>Previously, Yu-jinKim wrote…</i></summary><blockquote>

this function does 2 things:
- format data to extract information
- submit said information to the database
probably could be 2 functions
</blockquote></details>

i think as this is all one loop through the df it might be harder to split
where would you split it?
___
*[`pandora.py` line 175 at r2](https://reviewable.io/reviews/eastgenomics/clinvar_submissions/1#-O79AxRE0x8_8CD3xrtG:-O7Dj0YF184Ii1VIvlQz:b-896fix) ([raw file](https://github.com/eastgenomics/clinvar_submissions/blob/c5341cb51fd9bdc1aa81c4756315efe540276e8e/pandora.py#L175)):*
<details><summary><i>Previously, Yu-jinKim wrote…</i></summary><blockquote>

numpy not imported
</blockquote></details>

Done.
___
*[`pandora.py` line 193 at r2](https://reviewable.io/reviews/eastgenomics/clinvar_submissions/1#-O79B7T85TyRHz5FDbcs:-O79uKRI4ifMSGn537Vt:b-896fix) ([raw file](https://github.com/eastgenomics/clinvar_submissions/blob/c5341cb51fd9bdc1aa81c4756315efe540276e8e/pandora.py#L193)):*
<details><summary><i>Previously, Yu-jinKim wrote…</i></summary><blockquote>

why is it formatted like that?
```
parser = argparse.ArgumentParser(
        description="",
        formatter_class=(
            argparse.ArgumentDefaultsHelpFormatter
        )
    )
```
</blockquote></details>

Done.
___
*[`pandora.py` line 199 at r2](https://reviewable.io/reviews/eastgenomics/clinvar_submissions/1#-O79BLi3BlOfHjFRnCo2:-O7DtsXv-xARtmKIIgz6:b-5lcu55) ([raw file](https://github.com/eastgenomics/clinvar_submissions/blob/c5341cb51fd9bdc1aa81c4756315efe540276e8e/pandora.py#L199)):*
<details><summary><i>Previously, Yu-jinKim wrote…</i></summary><blockquote>

can have a chat about that if needed
</blockquote></details>

currently this is most likely going to run on ida, if there is a way of hiding api keys there?
___
*[`pandora.py` line 209 at r2](https://reviewable.io/reviews/eastgenomics/clinvar_submissions/1#-O79BeOI5UjAClOy63Dv:-O7DjDCB8Aej5VA53lnY:b-896fix) ([raw file](https://github.com/eastgenomics/clinvar_submissions/blob/c5341cb51fd9bdc1aa81c4756315efe540276e8e/pandora.py#L209)):*
<details><summary><i>Previously, Yu-jinKim wrote…</i></summary><blockquote>

your main is really bloated, with parsing of files, database stuff and pandas stuff going on. A lot can be put in functions
</blockquote></details>

Done.
___
*[`pandora.py` line 215 at r2](https://reviewable.io/reviews/eastgenomics/clinvar_submissions/1#-O79BxCmCJRo-h8xKQp_:-O79uMywAkgkh4DZ2Rx0:b-896fix) ([raw file](https://github.com/eastgenomics/clinvar_submissions/blob/c5341cb51fd9bdc1aa81c4756315efe540276e8e/pandora.py#L215)):*
<details><summary><i>Previously, Yu-jinKim wrote…</i></summary><blockquote>

i would try and keep related things close i.e. move this line just before it's used
</blockquote></details>

Done.
___
*[`pandora.py` line 216 at r2](https://reviewable.io/reviews/eastgenomics/clinvar_submissions/1#-O79C35cAH4M-opc12W4:-O7DjFDR3Y1YWT8ZQo7h:bdkuuzl) ([raw file](https://github.com/eastgenomics/clinvar_submissions/blob/c5341cb51fd9bdc1aa81c4756315efe540276e8e/pandora.py#L216)):*
<details><summary><i>Previously, Yu-jinKim wrote…</i></summary><blockquote>

can probably become a generic json loading function
</blockquote></details>

what do you mean by this, sorry?
___
*[`pandora.py` line 219 at r2](https://reviewable.io/reviews/eastgenomics/clinvar_submissions/1#-O79C8m80fN_u-1XyYjR:-O79uOkb24kPslnoVbRJ:b-896fix) ([raw file](https://github.com/eastgenomics/clinvar_submissions/blob/c5341cb51fd9bdc1aa81c4756315efe540276e8e/pandora.py#L219)):*
<details><summary><i>Previously, Yu-jinKim wrote…</i></summary><blockquote>

move this into a function and return the cursor
</blockquote></details>

Done.
___
*[`pandora.py` line 234 at r2](https://reviewable.io/reviews/eastgenomics/clinvar_submissions/1#-O79CQ0v126fznQ9GT9I:-O7DjJraDaX3ByYFc532:b-896fix) ([r [...]

2024-09-20 13:17 UTC, Yu-jinKim requested changes
> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/clinvar_submissions/1)* status: all files reviewed, 5 unresolved discussions (waiting on @kjwinfield)

___
*[`pandora.py` line 161 at r2](https://reviewable.io/reviews/eastgenomics/clinvar_submissions/1#-O79AiwI76mdXYvYnZ1e:-O7EZ9Dn7RTFvsNj944j:b9yy7j0) ([raw file](https://github.com/eastgenomics/clinvar_submissions/blob/c5341cb51fd9bdc1aa81c4756315efe540276e8e/pandora.py#L161)):*
<details><summary><i>Previously, kjwinfield (Katherine Winfield) wrote…</i></summary><blockquote>

i think as this is all one loop through the df it might be harder to split
where would you split it?
</blockquote></details>

i think i'd get the queries in a list and return that.
And pass that to an execute query function
But honestly i think the whole loop could be deleted by using an `apply` or something similar
___
*[`pandora.py` line 199 at r2](https://reviewable.io/reviews/eastgenomics/clinvar_submissions/1#-O79BLi3BlOfHjFRnCo2:-O7EXR7UB0MmfmhjUws7:bs01met) ([raw file](https://github.com/eastgenomics/clinvar_submissions/blob/c5341cb51fd9bdc1aa81c4756315efe540276e8e/pandora.py#L199)):*
<details><summary><i>Previously, kjwinfield (Katherine Winfield) wrote…</i></summary><blockquote>

currently this is most likely going to run on ida, if there is a way of hiding api keys there?
</blockquote></details>

i would need to ask about access to ida. Otherwise, i would have a dedicated config for this maybe?
___
*[`pandora.py` line 216 at r2](https://reviewable.io/reviews/eastgenomics/clinvar_submissions/1#-O79C35cAH4M-opc12W4:-O7EXv6A-vPNSbhaMBao:b-tqssqw) ([raw file](https://github.com/eastgenomics/clinvar_submissions/blob/c5341cb51fd9bdc1aa81c4756315efe540276e8e/pandora.py#L216)):*
<details><summary><i>Previously, kjwinfield (Katherine Winfield) wrote…</i></summary><blockquote>

what do you mean by this, sorry?
</blockquote></details>

```
def load_json_file(file_name):
    with open(args.config) as f:
        return json.load(f)
```

it's mostly a preference thing. I dislike handling files in the main
___
*[`utils/utils.py` line 16 at r2](https://reviewable.io/reviews/eastgenomics/clinvar_submissions/1#-O79LzoSAvKMc8Ur79pU:-O7EW75I8BwLIE-MQav3:b-w8o3vu) ([raw file](https://github.com/eastgenomics/clinvar_submissions/blob/c5341cb51fd9bdc1aa81c4756315efe540276e8e/utils/utils.py#L16)):*
<details><summary><i>Previously, kjwinfield (Katherine Winfield) wrote…</i></summary><blockquote>

Done. Win wrote all of the functions in this script, so I can adjust to match my style?
</blockquote></details>

as long as it's consistent with the repo i don't mind
___
*[`utils/utils.py` line 147 at r2](https://reviewable.io/reviews/eastgenomics/clinvar_submissions/1#-O79PCB96MUbhDbTgtUS:-O7EWFPXDSUgF-YOXhUW:bt148s6) ([raw file](https://github.com/eastgenomics/clinvar_submissions/blob/c5341cb51fd9bdc1aa81c4756315efe540276e8e/utils/utils.py#L147)):*
<details><summary><i>Previously, kjwinfield (Katherine Winfield) wrote…</i></summary><blockquote>

by "wrong" do you mean the style is different or that the info is incorrect?
it looks correct to me
</blockquote></details>

info is incorrect, argument name was `filename` and `variant` in the docstring.
Looks good now


<!-- Sent from Reviewable.io -->

2024-10-07 10:10 UTC, merged